#!/usr/bin/env node
/**
 * Service-worker build (W7b) — the delivery repo's pattern, transplanted: compile sw/sw.ts to
 * public/sw.js with esbuild AFTER `next build` (no Next plugin — Serwist/Turbopack incompat), with
 * a @serwist/build content-hashed precache manifest over public/.
 *
 * QR divergence from the delivery source: NO page-shell precache entries. The root layout is
 * force-dynamic (per-request CSP nonce), so no HTML document is precacheable — documents are
 * network-only and the offline fallback is a synthetic response embedded in the SW itself
 * (see sw/sw.ts). The precache is public/ assets only.
 *
 * ⚠️ turbo.json's build task lists public/sw.js* in `outputs` — a warm turbo cache must replay
 * the SW artifact or CI/Vercel ship without it (the cache-blindness trap).
 */

import { build } from "esbuild";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { existsSync } from "fs";
import { getManifest } from "@serwist/build";

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(__dirname, "..");

const SW_SRC = resolve(appRoot, "sw/sw.ts");
const SW_DEST = resolve(appRoot, "public/sw.js");

async function buildServiceWorker() {
  if (!existsSync(SW_SRC)) {
    console.error(`[build-sw] source not found: ${SW_SRC}`);
    process.exit(1);
  }

  const { manifestEntries, count, size } = await getManifest({
    globDirectory: resolve(appRoot, "public"),
    globPatterns: ["**/*.{png,jpg,jpeg,webp,avif,svg,ico,woff,woff2}"],
    // W22b — the precache is the APP SHELL's offline budget, so it holds only what the running page
    // actually fetches. Everything below is requested by something else entirely, over the normal
    // network, at a moment that is never offline-critical:
    //   • email-logo.png — fetched by EMAIL CLIENTS via an absolute URL (emails/MmsEmailLayout.tsx).
    //     117KB, the single largest entry, and the app itself never requests it.
    //   • icon-192/512 + both maskables — fetched by the OS/launcher at INSTALL time, never by a page.
    //     Precaching them would have pushed every diner on teahouse wifi from 261KB to ~506KB for
    //     bytes their browser will not ask this cache for.
    // Deliberately KEPT: logo.png (the header lockup + receipt card render it) and icon.svg (the
    // running tab's favicon).
    globIgnores: [
      "sw.js",
      "sw.js.map",
      "email-logo.png",
      "icon-192.png",
      "icon-512.png",
      "icon-maskable-512.png",
      "icon-maskable.svg",
    ],
    dontCacheBustURLsMatching: /\.[a-f0-9]{8,}\./,
    maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
  });

  try {
    await build({
      entryPoints: [SW_SRC],
      outfile: SW_DEST,
      bundle: true,
      minify: process.env.NODE_ENV === "production",
      format: "iife",
      target: ["chrome90", "firefox90", "safari15"],
      define: {
        "self.__SW_MANIFEST": JSON.stringify(manifestEntries),
        "process.env.NODE_ENV": '"production"',
      },
      banner: {
        js: `// Generated by scripts/build-sw.mjs — do not edit. Precache: ${count} entries, ${(size / 1024).toFixed(1)}KB\n`,
      },
    });
    console.log(
      `[build-sw] built ${SW_DEST} (precache: ${count} entries, ${(size / 1024).toFixed(1)}KB)`,
    );
  } catch (error) {
    console.error("[build-sw] failed:", error);
    process.exit(1);
  }
}

buildServiceWorker();
