import type { CartTotals } from "@mms/db";
import { taxRate } from "./tax";

/**
 * W8a — the charge arithmetic, lifted VERBATIM out of `getCartTotals`.
 *
 * Why this file exists: `getCartTotals` (`lib/totals.ts`) is the single authority for what a diner is
 * charged, and it was untestable — `import "server-only"` plus three I/O reads (a PostgREST select and
 * two RPCs) meant the only way to exercise it was to mock a chained query builder, which tests the
 * mock rather than the math. The arithmetic is 100% pure, so it moves here and `getCartTotals` keeps
 * exactly its old signature, doing the reads and calling this.
 *
 * ⚠️ **Charged-amount discipline.** The load-bearing expressions:
 *   • both `Number()` coercions on the DB-typed fields,
 *   • the CLAMP ORDER — promo clamps to the subtotal, then reward clamps to what remains AFTER it,
 *   • `Math.round` placement OUTSIDE the ratio (`round(d * (t/s))`, never `round(d*t)/s`),
 *   • the `restaurantBaseCents === 0` tip guard (NOT a "pure grocery" flag — see below).
 *
 * W16a (owner directive, 2026-08-15): the 5% service charge is RETIRED. `serviceChargeCents`
 * remains in the shape as a constant 0 (SQL params / share ledger / stored snapshots keep their
 * contract). W17a: the menu price a diner is charged is the POS price itself — no mode markup.
 *
 * Tested by `totals-math.test.ts`, whose expected values are shell-computed literals — never
 * generated by running this function.
 */

/**
 * One chargeable cart line as the totals engine sees it — field-for-field the columns
 * `getCartTotals` selects, with the DB's `number | string` widening already resolved by the caller.
 *
 * ⚠️ `taxCents` is PER UNIT, not per line (`cart.ts`/`staff-cart.ts`/`grocery.ts` all store
 * `lineTax(unitPriceCents, …)`), and it is read here ONLY as a boolean taxable-or-not flag — which is
 * the root of OPEN-ITEMS **M6**: a sub-6¢ taxable line rounds to `tax_cents = 0` and reads exempt.
 */
export type TotalsLine = {
  qty: number;
  unitPriceCents: number;
  taxCents: number;
  /** `draft | fired | in_progress | served | voided` — only `voided` is excluded from the charge. */
  state: string;
  comped: boolean;
  fulfillment: "dinein" | "togo" | "grocery";
};

/**
 * @param lines            every cart line, INCLUDING voided/comped ones (this function excludes them)
 * @param promoCentsRaw    the raw `mms_promo_discount` return (caller applies `?? 0`)
 * @param rewardCentsRaw   the raw `mms_reward_discount` return (caller applies `?? 0`)
 * @param tipRate          the diner's chosen rate; forced to 0 on a basket with no restaurant lines
 */
/**
 * M22 — how much of the applied coupon's face this basket cannot absorb, and therefore how much the
 * diner LOSES by paying now. 0 when there is nothing to disclose.
 *
 * The owner's call (2026-08-25) was **burn in full, but disclose it**: the coupon stays single-use,
 * `mms_redeem_cart_reward` keeps flipping `redeemed_at` unconditionally, and the diner is told before
 * they pay so the choice is theirs. This is the whole of "disclose it" — a surface that renders
 * nothing when this is 0 is correct.
 *
 * It lives here, not in the checkout component, for the reason W17 paid for twice: a rule left in
 * `Checkout.tsx` sits outside `check-money-coverage`'s MONEY_PATHS and cannot be guarded at all.
 *
 * ⚠️ Gated on ATTACHMENT (`rewardFaceCents > 0`), not on the applied amount — and the first draft of
 * this function had it the other way round, on the argument that "a disclosure with no reward row to
 * point at is noise". Codex round 1 (P1) showed that argument inverts the case it was meant to
 * protect. `rewardFaceCents > 0` means exactly "an unredeemed coupon is attached to this cart"
 * (`mms_reward_discount` reads `qr_carts.applied_reward_id`; it never looks at the lines), so the
 * applied amount falling to 0 — a basket voided or comped away under an attached coupon — is not the
 * quiet case, it is the WORST one: the entire face is at risk and the diner is closest to losing it.
 * Gating on the applied amount silenced the warning and, because the row keys on the same value, took
 * the Remove control away with it. The row and the warning both key on attachment now.
 */
export function rewardShortfallCents(
  totals: Pick<CartTotals, "rewardCents" | "rewardFaceCents">,
): number {
  if (totals.rewardFaceCents <= 0) return 0;
  return Math.max(totals.rewardFaceCents - totals.rewardCents, 0);
}

export function computeTotals(
  lines: TotalsLine[],
  promoCentsRaw: number,
  rewardCentsRaw: number,
  tipRate: number,
): CartTotals {
  // A voided OR comped line is charged at $0 (S2.3) — exclude it from the chargeable base everywhere
  // (mms_promo_discount + the settle reconciles apply the SAME predicate, so they all agree). A line that
  // predates S2 has state 'draft' / comped false, so this is a no-op for an un-voided cart.
  // NOTE: only `voided` is excluded by state — `fired`/`in_progress`/`served` lines are all charged,
  // correctly (the food exists). Do not restate this rule as "only draft lines are charged".
  const items = lines.filter((i) => i.state !== "voided" && !i.comped);
  // All integer cents — no float rounding on the base sums.
  const subtotalCents = items.reduce((a, i) => a + Number(i.unitPriceCents) * i.qty, 0);
  // Clamp to the (voided/comped-excluded) subtotal as belt-and-suspenders: mms_promo_discount already
  // excludes the same lines, so this only bites if the two ever drift — never letting a discount exceed
  // the chargeable base (which would drive a negative total).
  // M22 — the REWARD clamps first, and the promo takes what is left. The combined discount is
  // identical either way (both orders equal `min(promo + reward, subtotal)`, proven by CASE B and the
  // boundary sweep below), so nobody's total moves; the order only decides WHICH instrument absorbs
  // the clamp. That is not a wash, because the two are not alike when clamped:
  //
  //   · a reward coupon is single-use, personal, and DESTROYED on redemption — `mms_redeem_cart_reward`
  //     flips `redeemed_at` unconditionally, so every cent the clamp discards is gone for that one
  //     diner, permanently;
  //   · a promo code survives being clamped. Its budget is a REDEMPTION COUNT, consumed by
  //     `p_discount_cents > 0` at fulfillment (`mms_fulfill_order`) — not by value — so it costs the
  //     same one redemption whether it delivers its full face or a penny of it.
  //
  // Clamping the destructible instrument first was strictly the worse of two identical-priced
  // choices. Reward-first removes the promo collision entirely: a coupon can now only lose value
  // when the whole chargeable subtotal is smaller than its face — which is the case the diner is
  // told about (`rewardFaceCents` below), per the owner's call to burn in full but disclose.
  const rewardCents = Math.min(rewardCentsRaw, subtotalCents);
  // Clamped to what REMAINS so the combined discount never exceeds the chargeable base (no negative
  // total). discountCents folds both → tax base, total, the order snapshot and the loyalty net-spend
  // all treat the two as one discount, uniformly.
  const promoCents = Math.min(promoCentsRaw, Math.max(subtotalCents - rewardCents, 0));
  const discountCents = promoCents + rewardCents;
  const netCents = subtotalCents - discountCents;
  // Tax on the discounted TAXABLE base only (CDTFA) — not a pro-rata of the rounded aggregate,
  // so a flat promo across mixed taxable/exempt lines stays correct. Taxable lines have tax > 0.
  const taxableBaseCents = items.reduce(
    (a, i) => a + (Number(i.taxCents) > 0 ? Number(i.unitPriceCents) * i.qty : 0),
    0,
  );
  const discOnTaxableCents =
    subtotalCents > 0 ? Math.round(discountCents * (taxableBaseCents / subtotalCents)) : 0;
  const taxCents = Math.round((taxableBaseCents - discOnTaxableCents) * taxRate());
  // W16a — the 5% SB-1524 service charge is RETIRED (owner directive, 2026-08-15). It was briefly
  // replaced by a per-mode price markup; W17a retired that too, so the charged unit price is now
  // the bare POS price. `serviceChargeCents` stays in the CartTotals shape as a constant 0 so the
  // SQL fulfill params, share ledger, webhook reconcile, and stored snapshots keep their contract —
  // historical orders still render their real stored values.
  //
  // The RESTAURANT base survives for one job: the tip gate. No tip ask on a pure-grocery basket
  // (no grocery self-checkout prompts one) — forcing it to 0 HERE covers every caller identically:
  // create-intent mints the amount and the webhook recomputes the same breakdown from
  // metadata.tipRate, so the reconcile can never mismatch.
  // ⚠️ The gate is `restaurantBaseCents === 0`, i.e. "no restaurant VALUE", not "no restaurant
  // lines". A zero-priced non-grocery line leaves this 0 while the client's own `pureGrocery` flag
  // says otherwise — OPEN-ITEMS **M26**. Behaviour preserved as-is.
  const restaurantBaseCents = items.reduce(
    (a, i) => a + (i.fulfillment === "grocery" ? 0 : Number(i.unitPriceCents) * i.qty),
    0,
  );
  const serviceChargeCents = 0;
  const tipCents = restaurantBaseCents === 0 ? 0 : Math.round(netCents * tipRate);
  return {
    subtotalCents,
    discountCents,
    rewardCents,
    // M22 — the coupon's FACE value, so a surface can tell "you used a $5 reward" from "your $5
    // reward only had $4 of room here." Derived from the same raw the clamp reads, never a second
    // lookup: a value quoted from a different read is exactly how the burn went unnoticed. Equal to
    // `rewardCents` in every case except the one worth disclosing.
    rewardFaceCents: Math.max(rewardCentsRaw, 0),
    promoCents,
    serviceChargeCents,
    taxCents,
    tipCents,
    totalCents: netCents + serviceChargeCents + taxCents + tipCents,
  };
}
