-- W19 — the menu voice, completed (owner: "New menu items lacks the vibrant fun descriptions of
-- older items"). The W17d-2 batch shipped 4–10-word factual captions; the house voice (seed.sql's
-- W5c·r2 block, written to the owner's earlier "more elaborate, engaging, fun") is ~12–25 words:
-- a concrete, ingredient-true description, an em-dash pivot, then a three-beat cadence or a
-- personality kicker. This brings the 31 W17d-2 items — plus the six W15-era stragglers that
-- predate the voice pass (veggie-fritters … pop-soda) — up to that bar.
--
-- HONESTY RULE (the house rule, kept): no invented ingredients or claims — every ingredient named
-- below already appears in the item's prior description or its own name; "the regulars' pick"
-- (SHARK) is backed by the POS export (top-selling beverage, 501 units Jan–Jul 2026).
--
-- The Burmese is the seed's warmer-but-restrained diaspora register — NOT a literal translation of
-- the English jokes — and remains Claude-authored PENDING the owner's native check (K15), same flag
-- as every MY string in this repo.
--
-- Value-stable and therefore idempotent (the W5c·r2 precedent): re-running writes identical values.
update public.menu_items as m
set description_en = v.d,
    description_my = v.my
from (
  values
    ('pork-tamarind-stew',
     'Pork braised down with tamarind until the sour and the rich stop arguing — deep, dark, spoon-tender.',
     'ဝက်သားကို မကျည်းနဲ့ ဖြည်းဖြည်းချင်း နှပ်ထားတာ — ချဉ်ချဉ်နက်နက် ဇွန်းနဲ့ပြေတဲ့အထိ နူးပါတယ်။'),
    ('ngapi-sambal',
     'Ngapi fried with dried shrimp and chili into a fierce, fragrant relish — a little goes far, and never far enough.',
     'ငပိကို ပုဇွန်ခြောက်၊ ငရုတ်သီးနဲ့ ကြော်ထားတာ — နည်းနည်းလေးနဲ့ အများကြီးစားလို့ရပါတယ်။'),
    ('sour-water-spinach',
     'Water spinach in a puckery sour broth — the bright, brothy counterpoint your curry is asking for.',
     'ကန်စွန်းရွက် ချဉ်ရည်လေး — ဟင်းလေးအိုးနဲ့ တွဲသောက်ရင် အထူးလိုက်ဖက်ပါတယ်။'),
    ('bean-fritters',
     'Split-pea fritters fried to order — crackling outside, creamy inside, gone before they cool.',
     'ပဲကပ်ကြော် — အပြင်ကြွပ်ကြွပ် အထဲနူးနူး၊ မအေးခင် ကုန်တတ်ပါတယ်။'),
    ('beef-jerky',
     'House beef jerky, grilled and pounded tender — chewy, smoky, dangerously snackable.',
     'အမဲခြောက်ကို မီးဖုတ်ပြီး ထောင်းထားတာ — ဝါးလေ အရသာထွက်လေပါပဲ။'),
    ('mohinga-soup-side',
     'A side bowl of our mohinga broth — catfish-lemongrass comfort by the ladle.',
     'ဟင်းခါးရည် တစ်ပွဲလေး — ငါးရည်မွှေးမွှေး နွေးထွေးစရာပါ။'),
    ('sanwin-makin',
     'Semolina cake baked with coconut and butter — golden, chewy, the teahouse dessert that never left.',
     'ဆနွင်းမကင်း — အုန်းနို့၊ ထောပတ်နဲ့ ဖုတ်ထားတဲ့ လက်ဖက်ရည်ဆိုင် အချိုပွဲ ဂန္ထဝင်ပါ။'),
    ('catfish-head-mon',
     'Catfish head curry the Mon way — the cut connoisseurs fight over, simmered rich.',
     'ငါးခေါင်းကို မွန်နည်းအတိုင်း ချက်ထားတာ — စားတတ်သူတွေ အရင်လုကြတဲ့ အပိုင်းပါ။'),
    ('silurus-dried-fried',
     'Dried silurus catfish fried crisp — salty, brittle, made for a mountain of rice.',
     'ငါးကျည်းခြောက်ကြော် — ငန်ငန်ကြွပ်ကြွပ်၊ ထမင်းပူပူနဲ့ အတည့်ဆုံးပါ။'),
    ('kufee',
     'Chilled milk cream, teahouse style — cold, silky, quietly famous.',
     'ကူဖီး နို့မလိုင်အေးလေး — အေးအေးဆိမ့်ဆိမ့်၊ သိသူသိတဲ့ အရသာပါ။'),
    ('salted-fish-pounded',
     'Salted fish pounded with aromatics and fried — loud, salty, absolutely worth it.',
     'ငါးခြောက်ကို ထောင်းပြီးကြော်ထားတာ — အငန်ရသာပြင်းပြင်း၊ ထမင်းကုန်စေတတ်ပါတယ်။'),
    ('stir-fry-water-spinach',
     'Water spinach flash-fried over high heat — glossy, green, gone in minutes.',
     'ကန်စွန်းရွက်ကြော် — မီးအားပြင်းပြင်းနဲ့ ကြော်ထားလို့ စိမ်းစိုပြောင်လက်ပါတယ်။'),
    ('chicken-dregea',
     'Chicken simmered with dregea shoots — an upcountry green you rarely find stateside.',
     'ကြက်သားနဲ့ ဂွေးတောက် — ဒီနားမှာ ရှာရခက်တဲ့ တောရွက်ဟင်းပါ။'),
    ('chicken-salad',
     'Shredded chicken salad, Burmese-style — bright, punchy, built to share.',
     'ကြက်သားသုပ် — ချဉ်စပ်လတ်ဆတ်၊ မျှစားလို့ကောင်းတဲ့အမျိုးပါ။'),
    ('stir-fry-mixed-veggie',
     'Mixed greens hit with garlic and high heat — crisp, clean, louder than a side has any right to be.',
     'အစိမ်းစုံကို ကြက်သွန်ဖြူနဲ့ မီးပြင်းကြော် — ကြွပ်ကြွပ်ဆတ်ဆတ် စိမ်းစိုပါတယ်။'),
    ('pork-fermented-bean',
     'Pork cooked down with fermented soybean — funky, savory, deeply Burmese.',
     'ဝက်သားကို ပဲငပိနဲ့ ချက်ထားတာ — မြန်မာ့အရသာ စစ်စစ်ပါ။'),
    ('snakehead-dried',
     'Dried snakehead grilled over flame — smoky, intense, a monsoon-larder classic.',
     'ငါးရံ့ခြောက် မီးကင် — မီးခိုးနံ့သင်းသင်းနဲ့ ရသာပြင်းပါတယ်။'),
    ('goat-brains',
     'Goat brains curry — silky, rich, for the table’s bravest spoon.',
     'ဆိတ်ဦးနှောက်ဟင်း — နူးညံ့ဆိမ့်နက်၊ ရဲရင့်တဲ့ဇွန်းအတွက်ပါ။'),
    ('salted-fish-eggplant',
     'Salted fish and eggplant braised soft together — smoky-salty meets silky, and both win.',
     'ငါးခြောက်နဲ့ ခရမ်းသီး အတူနှပ်ထားတာ — အငန်နဲ့အနူး လိုက်ဖက်လွန်းပါတယ်။'),
    ('shrimp-crispy-fish-sauce',
     'Crispy shrimp tossed in a spicy fish-sauce glaze — sticky, fiery, impossible to stop.',
     'ပုဇွန်ကြော်ကို ငံပြာရည်စပ်စပ်နဲ့ လူးထားတာ — စပ်စပ်ငန်ငန် ရပ်လို့မရအောင်ပါ။'),
    ('coconut-sago',
     'Sago pearls in sweet coconut milk — cool, gentle, the quiet way to end big flavors.',
     'အုန်းနို့ထဲက သာကူလုံးလေးတွေ — အေးအေးချိုချို၊ နောက်ဆုံးပိတ် ချိုမြိန်စရာပါ။'),
    ('balachaung-side',
     'A small side of balachaung — the crunchy, garlicky upgrade everything on the table deserves.',
     'ဘာလချောင် တစ်ပွဲစာလေး — စားပွဲပေါ်က အရာအားလုံးကို ပိုကောင်းစေပါတယ်။'),
    ('grilled-fish',
     'Whole fish grilled over flame — charred edges, juicy middle, no shortcuts.',
     'ငါးတစ်ကောင်လုံး မီးကင် — အနားကြွပ်ကြွပ် အသားစိုစို၊ ဖြတ်လမ်းမပါပါ။'),
    ('fermented-sesame-salad',
     'Fermented sesame salad — tart, nutty, an upcountry rarity worth ordering twice.',
     'နှမ်းဖတ်ချဉ်သုပ် — ချဉ်ချဉ်ဆိမ့်ဆိမ့်၊ တွေ့ခဲတဲ့ တောင်ပေါ်အရသာပါ။'),
    ('dried-goat',
     'Dried goat, grilled and pounded — chewy, concentrated, fiercely loved.',
     'ဆိတ်သားခြောက် — မီးဖုတ်ပြီး ထောင်းထားလို့ ဝါးရင်း ရသာနက်ပါတယ်။'),
    ('fresh-fruits',
     'A platter of the season’s fruit, cut fresh — bright, cold, exactly enough.',
     'ရာသီပေါ် သစ်သီးစုံ လတ်လတ်ဆတ်ဆတ် — အေးမြချိုမြိန်ပါတယ်။'),
    ('bombay-duck-grilled',
     'Bombay duck grilled till the edges crisp — briny, delicate, coastal to the bone.',
     'အာဗြဲခြောက် မီးဖုတ် — ပင်လယ်နံ့သင်းသင်း၊ ညင်သာတဲ့အရသာပါ။'),
    ('oil-rice-with-peas',
     'Oil-drizzled rice with boiled peas — the humble breakfast that raised half of Burma.',
     'ပဲပြုတ်နဲ့ ထမင်းဆီဆမ်း — ရိုးရိုးလေးနဲ့ အားဖြစ်စေတဲ့ မနက်စာပါ။'),
    ('kayah-sausages',
     'Kayah-style pork sausages — smoky, savory, Kayah State’s pride.',
     'ကယားဝက်အူချောင်း — မီးခိုးနံ့လေးနဲ့ ကယားပြည်ရဲ့ ဂုဏ်ယူစရာပါ။'),
    ('beef-fried-shredded',
     'Beef shredded and fried dry — savory strands with crisp edges, made for rice.',
     'အမဲသားကို မျှင်ထုတ်ကြော်ထားတာ — အနားကြွပ်ကြွပ်၊ ထမင်းနဲ့ အတည့်ဆုံးပါ။'),
    ('bottled-water',
     'Cold bottled water — clean, simple, zero drama.',
     'ရေသန့်ဗူး အအေး — ရိုးရိုးရှင်းရှင်းပါပဲ။'),
    ('veggie-fritters',
     'A basket of assorted vegetable fritters, fried crackling — the teahouse classic that starts every good story.',
     'အကြော်စုံ ကြွပ်ကြွပ်လေးတွေ — လက်ဖက်ရည်ဆိုင် ဂန္ထဝင်၊ စကားစပြောရင်း ကုန်သွားတတ်ပါတယ်။'),
    ('ngapi-and-veggies',
     'Pounded ngapi dip ringed with fresh and boiled vegetables — bold, briny, built for dunking.',
     'ငပိထောင်းနဲ့ ဟင်းသီးဟင်းရွက်စုံ — ရဲရင့်တဲ့အရသာ၊ တို့စရာအတွက် မွေးထားတာပါ။'),
    ('malar-spicy-beef',
     'Beef simmered in numbing-spicy mala chili oil — tingly, fiery, gloriously unfair to the rice.',
     'အမဲသားကို မာလာဆီစပ်စပ်ထဲ နှပ်ထားတာ — လျှာထုံစပ်ရှိန်းပြီး ထမင်းတွေ ကုန်ပါတယ်။'),
    ('white-peas',
     'Boiled white peas under fried onions and oil — humble, warm, quietly essential.',
     'ပဲပြုတ်ပေါ် ကြက်သွန်ကြော်နဲ့ ဆီဆမ်းထားတာ — ရိုးရိုးလေးပေမယ့် မရှိမဖြစ်ပါ။'),
    ('shark-energy-drink',
     'SHARK energy, 8.4 oz and ice-cold — the regulars’ pick.',
     'SHARK အားဖြည့်ဖျော်ရည် 8.4 oz အေးအေးလေး — ပုံမှန်လာသူတွေရဲ့ အကြိုက်ပါ။'),
    ('pop-soda',
     'Assorted 12 oz sodas, ice-cold — pick your can.',
     'ဆိုဒါအမျိုးမျိုး 12 oz ဗူးအေးအေး — ကြိုက်တာ ရွေးလိုက်ပါ။')
) as v(slug, d, my)
where m.slug = v.slug;
